### ISSUE TITLE
Add key bindings to reset and move between levels

### ISSUE THREAD

**Issue by euangoddard** [euangoddard/xmas-18#1]

**Comment by adampoczatek** [comment]
I suggest following bindings:

Esc: Reset
Enter: Next level
Shift + enter: Previous level

Thoughts?

**Comment by euangoddard** [comment]
I think `Esc` is a great call. I was thinking `Page Up` and `Page Down` to move between levels, but makes sense with those!

**Comment by adampoczatek** [comment]
I don't think my keyboard has `page up` and `page down` 😅 but there's no reason to bind to both?

**Comment by euangoddard** [comment]
Good point. The arrow keys bind to two sets of key codes for different keyboard layouts 👍
